import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Weather Wise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={{ margin: '0', padding: '0', height: "100%", }} lang="en">
      
      <body style={{ margin: '0', padding: '0', height: "100%" }}>{children}</body>
    </html>
  )
}
